

export const REQUEST_IMAGES = 'REQUEST_IMAGES';
export const REQUEST_IMAGES_SUCCESS = 'REQUEST_IMAGES_SUCCESS';
export const REQUEST_CATEGORIES_SUCCESS = 'REQUEST_CATEGORIES_SUCCESS';
export const REQUEST_CATEGORIES = 'REQUEST_CATEGORIES';
export const ADD_MORE_DATA = 'ADD_MORE_DATA';
export const ADD_ACTIVE_ID = 'ADD_ACTIVE_ID';


